/**
 * Central registry for Debug IDs to ensure consistency and prevent duplicates.
 * Format: PAGE-TYPE-NUMBER
 */
export const DEBUG_IDS = {
  // Main Layout (M)
  MAIN_LAYOUT: {
    SIDEBAR: 'M-SIDEBAR-001',
    USER_INFO_CARD: 'M-CARD-001',
    NAVIGATION: 'M-NAV-001',
    HEADER: 'M-HEADER-001',
    LOGOUT_BTN: 'M-BTN-001'
  },

  // Login Page (A)
  LOGIN: {
    CARD: 'A-CARD-001',
    TITLE: 'A-TITLE-001',
    USERNAME_FIELD: 'A-FIELD-001',
    PASSWORD_FIELD: 'A-FIELD-002',
    LOGIN_BTN: 'A-BTN-001',
    ERROR_ALERT: 'A-ALERT-001'
  },

  // Dashboard (D)
  DASHBOARD: {
    SUMMARY_CARD: 'D-CARD-001',
    PENDING_KEEPER_METRIC: 'D-METRIC-001',
    PENDING_TRANSPORT_METRIC: 'D-METRIC-002',
    PENDING_CONFIRM_METRIC: 'D-METRIC-003',
    IN_TRANSIT_METRIC: 'D-METRIC-004',
    PENDING_FINAL_CONFIRM_METRIC: 'D-METRIC-005',
    ACTIVE_ORDERS_METRIC: 'D-METRIC-006',
    RECENT_ORDERS_TABLE: 'D-TABLE-001',
    REFRESH_BTN: 'D-BTN-001',
    CREATE_OUTBOUND_BTN: 'D-BTN-002',
    VIEW_HISTORY_BTN: 'D-BTN-003'
  },

  // Order List (L)
  ORDER_LIST: {
    FILTER_SECTION: 'L-SECTION-001',
    SEARCH_INPUT: 'L-FILTER-001',
    STATUS_FILTER: 'L-FILTER-002',
    TYPE_FILTER: 'L-FILTER-003',
    DATE_RANGE_FILTER: 'L-FILTER-004',
    RESET_BTN: 'L-BTN-001',
    CREATE_BTN: 'L-BTN-002',
    REFRESH_BTN: 'L-BTN-003',
    ERROR_RETRY_BTN: 'L-BTN-004',
    EMPTY_ACTION_BTN: 'L-BTN-005',
    PAGINATION_PREV: 'L-BTN-006',
    PAGINATION_NEXT: 'L-BTN-007',
    ORDER_TABLE: 'L-TABLE-001',
    ORDER_NO_COL: 'L-COL-001',
    STATUS_COL: 'L-COL-002',
    VIEW_ACTION: 'L-ACTION-001'
  },

  // Order Create (C)
  ORDER_CREATE: {
    FORM: 'C-FORM-001',
    ORDER_TYPE_FIELD: 'C-FIELD-001',
    TARGET_LOCATION_FIELD: 'C-FIELD-007',
    RETURN_TIME_FIELD: 'C-FIELD-002',
    KEEPER_ORG_FIELD: 'C-FIELD-003',
    TEAM_LEADER_ORG_FIELD: 'C-FIELD-004',
    TOOL_SEARCH_FIELD: 'C-FIELD-005',
    USAGE_PURPOSE_SELECT: 'C-FIELD-008',
    TOOL_TABLE: 'C-TABLE-001',
    REMARK_FIELD: 'C-FIELD-006',
    SUBMIT_BTN: 'C-BTN-001',
    CANCEL_BTN: 'C-BTN-002',
    REMOVE_TOOL_BTN: 'C-BTN-007',
    OPEN_TOOL_SEARCH_BTN: 'C-BTN-008',
    NOTIFICATION_PREVIEW_PANEL: 'C-PANEL-001',
    TOOL_SEARCH_DIALOG: 'C-DIALOG-001',
    // Tool Search Dialog Inner Elements
    TS_FILTER_SECTION: 'C-SECTION-002',
    TS_TOOL_CODE_FILTER: 'C-FILTER-001',
    TS_TOOL_NAME_FILTER: 'C-FILTER-002',
    TS_DRAWING_NO_FILTER: 'C-FILTER-003',
    TS_SPEC_FILTER: 'C-FILTER-004',
    TS_LOCATION_FILTER: 'C-FILTER-005',
    TS_RESET_BTN: 'C-BTN-003',
    TS_SEARCH_BTN: 'C-BTN-004',
    TS_RESULT_TABLE: 'C-TABLE-002',
    TS_FOOTER_ACTION_AREA: 'C-ACTION-002',
    TS_CANCEL_BTN: 'C-BTN-005',
    TS_CONFIRM_BTN: 'C-BTN-006'
  },

  // Order Detail (OD)
  ORDER_DETAIL: {
    INFO_PANEL: 'OD-PANEL-001',
    TOOL_LIST_PANEL: 'OD-PANEL-002',
    LOG_TIMELINE: 'OD-PANEL-003',
    ACTION_LOG_CARD: 'OD-PANEL-004',
    ACTION_SECTION: 'OD-SECTION-001',
    KEEPER_CONFIRM_BTN: 'OD-BTN-001',
    KEEPER_REJECT_BTN: 'OD-BTN-002',
    TRANSPORT_NOTIFY_BTN: 'OD-BTN-003',
    FINAL_CONFIRM_BTN: 'OD-BTN-004',
    PRINT_BTN: 'OD-BTN-005',
    BACK_BTN: 'OD-BTN-006',
    SUBMIT_ORDER_BTN: 'OD-BTN-007',
    CANCEL_ORDER_BTN: 'OD-BTN-008',
    ERROR_RETRY_BTN: 'OD-BTN-009',
    BACK_TO_LIST_BTN: 'OD-BTN-010'
  },

  // Keeper Workspace (K)
  KEEPER: {
    PENDING_LIST: 'K-LIST-001',
    ORDER_CARD: 'K-CARD-001',
    QUICK_CONFIRM_BTN: 'K-BTN-001',
    REJECT_BTN: 'K-BTN-002',
    DETAIL_DRAWER: 'K-PANEL-001',
    REFRESH_BTN: 'K-BTN-003',
    TRANSPORT_PREVIEW_BTN: 'K-BTN-004',
    CONFIRM_BTN: 'K-BTN-005',
    SEND_NOTIFY_BTN: 'K-BTN-006',
    TRANSPORT_TYPE_SELECT: 'K-FIELD-001',
    TRANSPORT_ASSIGNEE_INPUT: 'K-FIELD-002',
    KEEPER_REMARK_TEXTAREA: 'K-FIELD-003',
    LOCATION_INPUT: 'K-FIELD-004',
    STATUS_SELECT: 'K-FIELD-005',
    DISPATCH_TRANSPORT_BTN: 'keeper.dispatch_transport_btn'
  },

  // Admin Page (U)
  ADMIN: {
    USER_LIST_CARD: 'U-CARD-001',
    CREATE_USER_BTN: 'U-BTN-001',
    REFRESH_BTN: 'U-BTN-002',
    KEYWORD_FILTER: 'U-FILTER-001',
    STATUS_FILTER: 'U-FILTER-002',
    ORG_FILTER: 'U-FILTER-003',
    QUERY_BTN: 'U-BTN-003',
    QUICK_STATUS_BTN: 'U-BTN-004',
    USER_FORM_CARD: 'U-CARD-002',
    LOGIN_NAME_FIELD: 'U-FIELD-001',
    DISPLAY_NAME_FIELD: 'U-FIELD-002',
    EMPLOYEE_NO_FIELD: 'U-FIELD-003',
    STATUS_SELECT: 'U-FIELD-004',
    DEFAULT_ORG_SELECT: 'U-FIELD-005',
    SUBMIT_BTN: 'U-BTN-005',
    RESET_FORM_BTN: 'U-BTN-006',
    RESET_PASSWORD_BTN: 'U-BTN-007'
  }
}
